source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'SuperDesigner' do
    
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 4.0.0'
pod 'Masonry', '~> 1.0.2'
pod 'IQKeyboardManager', '~> 4.0.10'
pod 'MJExtension', '~> 3.0.13'

pod 'Toast', '~> 3.1.0'

pod 'MJRefresh', '~> 3.1.12'

end
